[project]
name = "quanition-studio"
version = "1.0.0"
requires-python = ">=3.9"
dependencies = ["PySide6>=6.6", "python-docx>=1.0.0"]

[project.scripts]
quanition-studio = "quanition_studio.app:main"

[tool.setuptools.packages.find]
include = ["quanition_studio*"]
